/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/CL3vOk4APsx
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import { Carousel, CarouselItem } from "@/components/ui/carousel"
import { Card, CardContent } from "@/components/ui/card"
import { Dialog, DialogContent, DialogClose } from "@/components/ui/dialog"

export function CardCarousel() {
  const [selectedTier, setSelectedTier] = useState<string | null>(null)
  const [showModal, setShowModal] = useState(false)

  return (
    <div className="relative w-full max-w-5xl mx-auto">
      <Carousel className="flex gap-6 overflow-x-auto scroll-smooth snap-x snap-mandatory pb-6">
        <CarouselItem
          className="flex-none w-[320px] snap-center"
          onClick={() => {
            setSelectedTier("airpods")
            setShowModal(true)
          }}
        >
          <Card className="h-full bg-background shadow-lg rounded-2xl overflow-hidden">
            <img
              src="/airdrops.webp"
              alt="AirPods Pro"
              width="600"
              height="200"
              className="w-full h-[200px] object-cover"
              style={{ aspectRatio: "600/200", objectFit: "cover" }}
            />
            <CardContent className="p-6 flex flex-col gap-4">
              <h3 className="text-2xl font-semibold">AirPods Pro</h3>
              <p className="text-muted-foreground">Immersive sound, customizable fit, and intuitive controls.</p>
            </CardContent>
          </Card>
        </CarouselItem>
        <CarouselItem
          className="flex-none w-[320px] snap-center"
          onClick={() => {
            setSelectedTier("macbook")
            setShowModal(true)
          }}
        >
          <Card className="h-full bg-background shadow-lg rounded-2xl overflow-hidden">
            <img
              src="/macbook.jpg"
              alt="MacBook Air"
              width="600"
              height="200"
              className="w-full h-[200px] object-cover"
              style={{ aspectRatio: "600/200", objectFit: "cover" }}
            />
            <CardContent className="p-6 flex flex-col gap-4">
              <h3 className="text-2xl font-semibold">MacBook Air</h3>
              <p className="text-muted-foreground">
                Powerful performance, stunning Retina display, and all-day battery life.
              </p>
            </CardContent>
          </Card>
        </CarouselItem>
        <CarouselItem
          className="flex-none w-[320px] snap-center"
          onClick={() => {
            setSelectedTier("ipad")
            setShowModal(true)
          }}
        >
          <Card className="h-full bg-background shadow-lg rounded-2xl overflow-hidden">
            <img
              src="/ipad.jpg"
              alt="iPad Pro"
              width="600"
              height="200"
              className="w-full h-[200px] object-cover"
              style={{ aspectRatio: "600/200", objectFit: "cover" }}
            />
            <CardContent className="p-6 flex flex-col gap-4">
              <h3 className="text-2xl font-semibold">iPad Pro</h3>
              <p className="text-muted-foreground">
                The ultimate iPad experience with powerful performance and advanced features.
              </p>
            </CardContent>
          </Card>
        </CarouselItem>
        <CarouselItem
          className="flex-none w-[320px] snap-center"
          onClick={() => {
            setSelectedTier("watch")
            setShowModal(true)
          }}
        >
          <Card className="h-full bg-background shadow-lg rounded-2xl overflow-hidden">
            <img
              src="/applewatch.jpg"
              alt="Apple Watch"
              width="600"
              height="200"
              className="w-full h-[200px] object-cover"
              style={{ aspectRatio: "600/200", objectFit: "cover" }}
            />
            <CardContent className="p-6 flex flex-col gap-4">
              <h3 className="text-2xl font-semibold">Apple Watch</h3>
              <p className="text-muted-foreground">The ultimate personal health and fitness companion.</p>
            </CardContent>
          </Card>
        </CarouselItem>
      </Carousel>
      {showModal && (
        <Dialog open={showModal} onOpenChange={setShowModal}>
          <DialogContent className="bg-background p-8 rounded-2xl max-w-2xl w-full mx-auto">
            {selectedTier === "airpods" && (
              <div>
                <div className="flex items-start gap-6">
                  <img
                    src="/airdrops.webp"
                    alt="AirPods Pro"
                    width="300"
                    height="200"
                    className="rounded-lg object-cover"
                    style={{ aspectRatio: "300/200", objectFit: "cover" }}
                  />
                  <div>
                    <h2 className="text-2xl font-bold">AirPods Pro</h2>
                    <p className="text-muted-foreground">Immersive sound, customizable fit, and intuitive controls.</p>
                    <ul className="list-disc pl-6 mt-4">
                      <li>Active Noise Cancellation for immersive sound</li>
                      <li>Transparency mode for hearing the world around you</li>
                      <li>Customizable fit for all-day comfort</li>
                      <li>Sweat and water resistant</li>
                      <li>Up to 4.5 hours of listening time on a single charge</li>
                    </ul>
                  </div>
                </div>
              </div>
            )}
            {selectedTier === "macbook" && (
              <div>
                <div className="flex items-start gap-6">
                  <img
                    src="/macbook.jpg"
                    alt="MacBook Air"
                    width="300"
                    height="200"
                    className="rounded-lg object-cover"
                    style={{ aspectRatio: "300/200", objectFit: "cover" }}
                  />
                  <div>
                    <h2 className="text-2xl font-bold">MacBook Air</h2>
                    <p className="text-muted-foreground">
                      Powerful performance, stunning Retina display, and all-day battery life.
                    </p>
                    <ul className="list-disc pl-6 mt-4">
                      <li>Apple M1 chip for powerful performance</li>
                      <li>Stunning 13.3-inch Retina display</li>
                      <li>Up to 18 hours of battery life</li>
                      <li>Fanless design for silent operation</li>
                      <li>Lightweight and portable design</li>
                    </ul>
                  </div>
                </div>
              </div>
            )}
            {selectedTier === "ipad" && (
              <div>
                <div className="flex items-start gap-6">
                  <img
                    src="/ipad.jpg"
                    alt="iPad Pro"
                    width="300"
                    height="200"
                    className="rounded-lg object-cover"
                    style={{ aspectRatio: "300/200", objectFit: "cover" }}
                  />
                  <div>
                    <h2 className="text-2xl font-bold">iPad Pro</h2>
                    <p className="text-muted-foreground">
                      The ultimate iPad experience with powerful performance and advanced features.
                    </p>
                    <ul className="list-disc pl-6 mt-4">
                      <li>Powerful M1 chip for lightning-fast performance</li>
                      <li>Stunning 12.9-inch Liquid Retina XDR display</li>
                      <li>Advanced camera system with LiDAR Scanner</li>
                      <li>Supports Apple Pencil and Magic Keyboard</li>
                      <li>All-day battery life</li>
                    </ul>
                  </div>
                </div>
              </div>
            )}
            {selectedTier === "watch" && (
              <div>
                <div className="flex items-start gap-6">
                  <img
                    src="/applewatch.jpg"
                    alt="Apple Watch"
                    width="300"
                    height="200"
                    className="rounded-lg object-cover"
                    style={{ aspectRatio: "300/200", objectFit: "cover" }}
                  />
                  <div>
                    <h2 className="text-2xl font-bold">Apple Watch</h2>
                    <p className="text-muted-foreground">The ultimate personal health and fitness companion.</p>
                    <ul className="list-disc pl-6 mt-4">
                      <li>Tracks your daily activity and workouts</li>
                      <li>Measures your heart rate and blood oxygen levels</li>
                      <li>Provides ECG and fall detection features</li>
                      <li>Offers a range of customizable watch faces</li>
                      <li>Seamlessly integrates with your iPhone</li>
                    </ul>
                  </div>
                </div>
              </div>
            )}
            <DialogClose asChild>
              <button className="absolute top-4 right-4">
                <XIcon className="w-5 h-5" />
              </button>
            </DialogClose>
          </DialogContent>
        </Dialog>
      )}
    </div>
  )
}

function XIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}